### ISSUE TITLE
Update pelago/emogrifier dependency to ^2.0.0

### ISSUE THREAD

**Issue by oliverklee** [sandstorm/TemplateMailer#1]
Emogrifier 2.0.0 has been released, fixing a lot of bugs. If the new PHP >= 5.5 requirement is not a problem, the dependency should be updated to ^2.0.0.

**Comment by robregonm** [comment]
+1
Also, it adds support to PHP 7.2 (Currently, TemplateMailer doesn't work on PHP 7.2 due to this limitation)

**Comment by skurfuerst** [comment]
fixed :) thank you and sorry for the long delay!
