### ISSUE TITLE
TASK: Update emogrifier dependency to support PHP 8 environments

### ISSUE THREAD

**Issue by jobee** [sandstorm/TemplateMailer#12]
https://github.com/MyIntervals/emogrifier/releases

v5.0.0 supports PHP 8.0
v6.0.0 supports PHP 8.1

**Comment by jobee** [comment]
Just noticed, there is already a PR (#11 ) for that.
/cc @skurfuerst :-)

**Comment by kdambekalns** [comment]
My PR also allows PHP 8.2 and 8.3 to work…
